config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, :only => [:show]

  resources :yachts do
    resources :bookings, only: %i[new create]
     resources :reviews, only: %i[index new create]
     get '/booking_successful', to: "bookings#successful", as: :booking_successful
  end
     get '/my-bookings', to: 'bookings#index', as: :my_bookings
     delete '/bookings/:id', to: 'bookings#destroy', as: :delete_booking
     get 'bookings/:user_id', to: 'bookings#show', as: :booking
  resources :bookings, only: :update

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :yacht
  belongs_to :user
  has_one :review

  validates_presence_of :user_id, :yacht_id, :check_out_date, :check_in_date
  validate :before_today?

  validate :check_out_date_after_check_in_date

  enum status: [:accepted, :rejected, :pending]

  validates :check_in_date, :check_out_date, overlap: { scope: 'yacht_id',
                                                        message_content: 'overlaps with another booking.' }

  private

  def check_out_date_after_check_in_date
    return if check_out_date.blank? || check_in_date.blank?

    errors.add(:check_out_date, "must be after the check in date") if check_out_date < check_in_date
  end

  def before_today?
    errors.add(:check_in_date, "must be after today") if check_in_date < Date.today
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates_presence_of :rating, :content
  validates_length_of :content, maximum: 300, message: "Character limit is 300."
  validates :rating, numericality: { greater_than: 0, less_than: 6 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :yachts, dependent: :destroy
  has_many :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_presence_of :first_name, :last_name, :username, :address, :date_of_birth
  # validates :email, format: { with: /\w+@\w+.\w{2,}/ }
end

app/models/yacht.rb
class Yacht < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :reviews, through: :bookings
  has_many :bookings

  acts_as_taggable_on :categories

  $categories = [" Sailing Yacht", "Motor Yacht", "Gulet Yacht", "Cruising Yacht", "Luxury Yacht", "Sports Yacht", "Catamaran Yacht"]

  geocoded_by :location

  after_validation :geocode, if:
  :will_save_change_to_location?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name address username date_of_birth])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name address username date_of_birth])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: :new

  def index
    @user = current_user
    @bookings = policy_scope(Booking.where(user: current_user.id))
    authorize @bookings
  end

  def new
    @booking = Booking.new
    @yacht = Yacht.find(params[:yacht_id])
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @yacht = Yacht.find(params[:yacht_id])
    @booking.yacht = @yacht
    authorize @booking
    @booking.user = current_user
    if @booking.save
      redirect_to my_bookings_path
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:user_id])
    authorize @booking
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to my_bookings_path
  end

  def edit
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def update
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.update(booking_params)
    redirect_to user_path(current_user)
  end
  # def successful
  #   @bookings = Yacht.find(params[:yacht_id])
  #   authorize @bookings

  #   redirect_to my_bookings_path
  # end
  # def booking_status_params
  #   params.require(:booking_status).permit()
  # end

  def booking_params
    params.require(:booking).permit(:check_out_date, :check_in_date, :status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    authorize @review
    @review.booking = Booking.where(yacht: params[:yacht_id]).last
    if @review.save
      redirect_to yacht_path(params[:yacht_id])
    else
      redirect_to yachts_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    authorize User.find(params[:id])
    @yachts = @user.yachts
    @bookings = Booking.where(yacht_id: current_user.yachts)
  end
end

app/controllers/yachts_controller.rb
class YachtsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index

    @yachts = policy_scope(Yacht)
     if params["search"].present?
       @yachts = policy_scope(Yacht.near(params["search"]["location"]))
     else
       @yachts = policy_scope(Yacht)
     end

    @markers = @yachts.geocoded.map do |yacht|
      {
        lat: yacht.latitude,
        lng: yacht.longitude
      }
      # if params["search"]
      #   @filter = params["search"]["Categories"].concat(params["search"]["strengths"]).flatten.reject(&:blank?)
      #   @yachts = @filter.empty? ? Yacht.all : Yacht.all.tagged_with(@filter, any: true)
      # else
      #   @yachts = Yacht.all
      # end
    end
  end

  def new
    @yacht = Yacht.new
    authorize @yacht
  end

  def create
    @yacht = Yacht.new(yacht_params)
    @yacht.user = current_user
    authorize @yacht
    if @yacht.save
      redirect_to yachts_path
    else
      render :new
    end
  end

  def edit
    @yacht = Yacht.find(params[:id])
    authorize @yacht
  end

  def update
    @yacht = Yacht.find(params[:id])
    authorize @yacht
    @yacht.update(yacht_params)
    redirect_to user_path(current_user)
  end

  def destroy
    @yacht = Yacht.find(params[:id])
    authorize @yacht
    @yacht.destroy
    redirect_to user_path(current_user)
  end

  def show
    @yacht = Yacht.find(params[:id])
    authorize @yacht
    @markers = [{lng: @yacht.longitude, lat: @yacht.latitude}]
    @bookings = Booking.where('yacht_id = ?', params[:id])
    @reviews = Review.where(booking: @yacht)
    @review = Review.new
  end

  private

  def yacht_params
    params.require(:yacht).permit(:name, :description, :yacht_type, :length, :number_of_cabins,
                                  :rental_price,
                                  :user_id,
                                  :location,
                                  :guests, photo: [] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@yacht, @booking], url: yacht_bookings_path do |f| %>
<div class="row justify-content-center">
<%= f.input :check_in_date,
             as: :string, order: [:day, :month, :year], required: true, input_html: {class: "datepicker"} %>
</div>
<div class="row justify-content-center">
<%= f.input :check_out_date, as: :string, order: [:day, :month, :year], required: true, input_html: {class: "datepicker"}%>
</div>
<div class="row justify-content-center">
  <%= f.input :number_of_guests, collection: 1..yacht.guests %>
</div>
<div class="row justify-content-center">
<%= f.submit class: 'btn btn-primary form-btn' %>
</div>
<% end %>

app/views/bookings/index.html.erb
<%= render '/shared/navbar' %>

<div class="my-bookings-container">

<h1 class='my-3'>My bookings</h1>

<hr>
<div class="col">
      <% @bookings.each do |booking| %>
      <%= link_to booking_path(booking) do %>
        <div class="card_bookings">
          <h2 class="card-title">Yacht name: <%= booking.yacht.name %></h2>
          <div class="checkin-data">
            <p> Your check in date is: <%= booking.check_in_date.strftime('%a %d %b %Y') %></p>
            <p>Your check out date is: <%= booking.check_out_date.strftime('%a %d %b %Y') %></p>
          </div>
          <p><%= booking.yacht.description %></p>
          <p id="booking-status" data-booking-status="<%= booking.status %>">Status: <strong><%= booking.status.capitalize %></p> </strong>
          <%= link_to "Delete this booking", delete_booking_path(booking), method: :delete, data: {confirm: "Are you sure you want to delete #{booking.yacht.name}?"} %>
        </div>
        <% end %>
      <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<%= render '/shared/navbar' %>

<div class="text-center my-3">

<h2>Add a new booking</h2>

</div>
<div class="form-container">

<h3> <%= @yacht.name %> </h3>

<div class="booking-form">

<%= render "form", yacht: @yacht, booking: @booking %>
</div>

</div>

app/views/bookings/show.html.erb
<%= render '/shared/navbar' %>
<%= @booking.yacht.name %>
<%= @booking.yacht.description %>
£<%= (@booking.check_out_date - @booking.check_in_date) %>

app/views/bookings/successful.html.erb
<h2>Your booking was successful!</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= stylesheet_pack_tag 'application' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Yacht Me</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>


  </head>

  <body>

    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(https://www.sailuxeboat.com/wp-content/uploads/2019/04/1_sailuxe_home.jpg);">
  <%= render 'shared/navbar' %>
  <div class="container">
    <h1>Book a yacht <strong>whenever & wherever!</strong></h1>
  </div>
</div>
<div class="content-main" >
  <div class="left-img" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(https://heremag-prod-app-deps-s3heremagassets-bfie27mzpk03.s3.amazonaws.com/wp-content/uploads/2020/02/19120216/2E0ABCF2-4B95-43DE-A0F1-4B1D5F3A1053-1200x900.jpg);">
  </div>
  <div class="second">
    <div class="page-kpis">
      <div class="main-discription">
        <h2>200</h2>
        <p>Experiences</p>
      </div>
      <div class="main-discription">
        <h2>30</h2>
        <p>Locations</p>
      </div>
      <div class="main-discription">
        <h2>624</h2>
        <p>Yachts</p>
      </div>
      <div class="main-discription">
        <h2>9000</h2>
        <p>Members</p>
      </div>
    </div>
    <div class="right-img" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(https://features.boats.com/boat-content/files/2016/05/cruising-sailboat.jpg);">
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if controller_name == "pages"%>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path, class: "navbar-brand" do %>
        <h2>Yacht Me</h2>
    <% end %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto navbar-links">
        <li>
          <%= link_to "Yachts", yachts_path, class: "nav-link" %>
        </li>
        <% if signed_in? %>
          <li>
            <%= link_to "My bookings", my_bookings_path, class: "nav-link site-links" %>
          </li>
          <li>
            <%= link_to 'Add a new yacht', new_yacht_path, class: 'nav-link site-links'%>
          </li>
          <li>
            <%= link_to "Home", user_path(current_user), class: "nav-link site-links" %>
          </li>
          <li>
            <%= link_to "Log out", destroy_user_session_path , method: :delete, class: "nav-link site-links" %>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", new_user_session_path, class: "nav-link site-links" %>
          </li>
          <li>
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link site-links" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <% else %>
    <div class="navbar navbar-expand-sm navbar-light secondary-navbar-lewagon">
        <%= link_to root_path, class: "navbar-brand d-flex" do %>
          <h2>Yacht Me</h2>
        <% end %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto navbar-links-sec">
            <li>
              <%= link_to "Yachts", yachts_path, class: "nav-link" %>
            </li>
            <% if signed_in? %>
              <li>
                <%= link_to "My bookings", my_bookings_path, class: "nav-link site-links-sec" %>
              </li>
              <li>
                <%= link_to 'Add a new yacht', new_yacht_path, class: 'nav-link site-links-sec'%>
              </li>
              <li>
                <%= link_to "Home", user_path(current_user), class: "nav-link site-links" %>
              </li>
              <li>
                <%= link_to "Log out", destroy_user_session_path , method: :delete, class: "nav-link site-links-sec" %>
              </li>
            <% else %>
              <li>
                <%= link_to "Login", new_user_session_path, class: "nav-link site-links-sec" %>
              </li>
              <li>
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link site-links-sec" %>
              </li>
            <% end %>
          </ul>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<%= render 'shared/navbar' %>
<div class="user-bookings">
  <h2 id="bookings-title">Bookings Overview</h2>
  <% @bookings.each do |booking| %>
    <div class="booking-card">
      <div class="booking-card-user-info">
        <h5> <strong> <%= booking.user.username %></strong> want's to rent the <%= booking.yacht.name %> </h5>
        <p>Check In: <strong> <%= booking.check_in_date.strftime('%a %d %b %Y') %></strong></p>
        <p>Check Out: <strong> <%= booking.check_out_date.strftime('%a %d %b %Y') %></strong></p>
      </div>
      <div class="booking-card-status">
        <p>status: <strong><%= booking.status %></strong> </p>
      </div>
      <div class="booking-card-action">
        <h5><%= link_to 'Confirm', booking_path(booking, booking: { status: 'accepted' }), method: :patch, remote: true %></h5>
        <h5><%= link_to 'Reject', booking_path(booking, booking: { status: 'rejected' }), method: :patch, remote: true %></h5>
        <h5><%= link_to 'Pending', booking_path(booking, booking: { status: 'pending' }), method: :patch, remote: true %></h5>
      </div>
    </div>
  <% end %>
</div>

<div id="user-page">
  <div id="user-page-img" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(https://listings.classicyachtinfo.com/wp-content/uploads/listing-uploads/gallery/2020/08/Moonbeam-of-Fife-2017.jpg);">
  </div>
  <div >
    <h2 align="center">My Yachts Listings</h2>
    <% @yachts.each do |yacht| %>
      <div class="card-product user-cards">
        <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.d5A5BDorSA6qjx78D35hfgHaEK%26pid%3DApi&f=1" alt="Yacht19" class="card-img-top" />
        <div class="card-product-infos">
          <h2><%= yacht.name %></h2>
          <p><%= yacht.description %></p>
          <div id="user-action">
            <div class="yacht-delete">
              <%= link_to edit_yacht_path(yacht),
                method: :get do %>
                <i class="fas fa-edit"></i>
              <% end %>
            </div>
            <div class="yacht-delete">
              <%= link_to yacht_path(yacht),
                method: :delete,
                data: { confirm: "Are you sure?" } do %>
                <i class="far fa-trash-alt trash"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/yachts/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">

</div>

app/views/yachts/_specs.html.erb
<div class="card">
        <div class="card-header">
          Specification
        </div>
        <div class="card-body">
          <table>
            <tbody>
              <tr>
                <td width="145">Length</td>
                <td >
                <span><%= @yacht.length %></span>
                </td>
              </tr>
              <tr>
                <td>Cabins</td>
                <td>
                <span><%= @yacht.number_of_cabins %></span>
                </td>
              </tr>
              <tr>
                <td>Cruising Speed</td>
                <td>12 Knots</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

app/views/yachts/edit.html.erb
  <%= render 'shared/navbar' %>



<div class="form-container mt-3">
<div class="row justify-content-center ">

<h1>Edit your yacht</h1>

</div>
<div class="row justify-content-center">
<div class="booking-form form-fields">



<%= simple_form_for(@yacht) do |f| %>
<div class="row justify-content-center">
<%= f.input :name %>
</div>
<div class="row justify-content-center">
<%= f.input :description, input_html: {rows: 4} %>
</div>
<div class="row justify-content-center">
<%= f.input :length %>
</div>
<div class="row justify-content-center">
<%= f.input :yacht_type %>
</div>
<div class="row justify-content-center">
<%= f.input :number_of_cabins %>
</div>
<div class="row justify-content-center">
<%= f.input :rental_price %>
</div>
<div class="row justify-content-center">
<%= f.input :guests %>
</div>
<div class="row justify-content-center">
<%= f.input :location %>
</div>
<div class="row justify-content-center">
<%= f.input :photo, as: :file, label: false%> <!--add a file picture-->
</div>
<div class="row justify-content-center">
<%= f.submit class: 'btn btn-primary form-btn' %>
</div>
<% end %>
</div>
</div>
</div>

app/views/yachts/index.html.erb
<%= render 'shared/navbar' %>
<% if user_signed_in? %>
<% end %>
<!--Search a Yacht-->

<div class="center">
<div class="searchbox">
  <div class="row">
<%= simple_form_for :search, url: yachts_path, method: "GET", html: { class: 'form-inline search-form' } do |f| %>
  <%= f.input :location, input_html: {placeholder: "Where will you set sail?"} %>
  <div class="dropdown dropdown-yacht">
    <button class="btn btn-secondary dropdown-toggle yachtegories pad-small" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Yachtegories
  </button>
    <div class="dropdown-menu search-catgy">
      <div class="drop"></div>
    <%= f.input :category, label: "Categories", collection:$categories, as: :check_boxes, class: "dropdown-item" %>
    </div>
  </div>
  <%= f.submit "Search", class: "btn btn-primary btn-search pad-small" %>
  <!-- <%= link_to "Reset", root_path %> -->
<% end %>
</div>
</div>
</div>


   <div class="main-container">
   <hr>
   <div class="cards">
      <% @yachts.each do |yacht| %>
      <div class="card">
         <%= link_to yacht_path(yacht) do %>
         <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.d5A5BDorSA6qjx78D35hfgHaEK%26pid%3DApi&f=1" alt="Yacht19" class="card-img-top">
         <% end %>
         <div class="card-body">
         <div class="card-trip-infos">
           <div>
              <h2><%= yacht.name %></h2>
              <p class="description"><%= yacht.description %></p>
              <p class="card-trip-address" ><i class="fas fa-map-marker-alt"></i> <em><%= yacht.location %></em></p>
           </div>
         </div>
         <div class="card-trip-type">
          <h2><i class="fas fa-user-friends"></i> <strong><%= yacht.guests %> </strong> </h2>
          <h2><i class="fas fa-bed"></i> <strong><%= yacht.number_of_cabins %> </strong></h2>
          <h2> <strong><%= yacht.yacht_type %></strong> </h2>
         </div>
         <div class="card-trip-pricing">
            <h2 >£<%= yacht.rental_price%> per night</h2>
         </div>
      </div>
      </div>
      <% end %>
         </div>
          <div id="map"style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
     </div>
   </div>
   <!-- Change the token below (https://www.mapbox.com/account/access-tokens/) -->

</div>

app/views/yachts/new.html.erb
  <%= render 'shared/navbar' %>



<div class="form-container mt-3">
<div class="row justify-content-center ">

<h1>Add a new yacht</h1>

</div>
<div class="row justify-content-center">
<div class="booking-form form-fields">



<%= simple_form_for(@yacht) do |f| %>
<div class="row justify-content-center">
<%= f.input :name %>
</div>
<div class="row justify-content-center">
<%= f.input :description %>
</div>
<div class="row justify-content-center">
<%= f.input :length %>
</div>
<div class="row justify-content-center">
<%= f.input :yacht_type %>
</div>
<div class="row justify-content-center">
<%= f.input :number_of_cabins %>
</div>
<div class="row justify-content-center">
<%= f.input :rental_price %>
</div>
<div class="row justify-content-center">
<%= f.input :guests %>
</div>
<div class="row justify-content-center">
<%= f.input :location %>
</div>
<div class="row justify-content-center">
<%= f.input :photo, as: :file, input_html: { multiple: true }, label: false%> <!--add a file picture-->
</div>
<div class="row justify-content-center">
<%= f.submit class: 'btn btn-primary form-btn' %>
</div>
<% end %>
</div>
</div>
</div>

app/views/yachts/show.html.erb
<%= render 'shared/navbar' %>
<section id='hero'>
  <% if @yacht.photo.present? %>
    <%= cl_image_tag @yacht.photo.key, width: 1920, crop: :fill %>
    <% else %>
      <%= image_tag 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1950&q=80' %>
    <% end %>
</section>
<div class="container-fluid">
  <div class="row" id='showHeader'>
    <div class='col d-flex flex-row justify-content-between align-items-center mt-5'>
    <div class='d-flex flex-row align-items-baseline'>
      <h1><%= @yacht.name %></h1>
      <h2 class='ml-5'><%= @yacht.rental_price %>€/night</h2>
      <h3>
        <div class='ml-5'>
          <h2 class="fas fa-users"></h2>
          <%= @yacht.guests %>
        </div>
      </h3>
    </div>
      <div>
        <%= link_to "Book this Yacht", new_yacht_booking_path(@yacht), class: "btn btn-primary btn-large btn-lg btn-search" %>
      </div>
    </div>
      <!-- <a href="#" class="btn btn-primary">Book this Yacht</a> -->
  </div>
  <div class="row justify-content-between mt-3" id='showBody'>
    <div class="col-8">
      <p><%= @yacht.description %></p>
    </div>
    <div class="col-4">
    <%= render 'specs' %>
    </div>
   <div class="review container-fluid">
      <h3>Reviews</h3>
        <% @reviews.each do |review| %>
        <div class="row">
          <div class="col">
            <%= review.content %>
            <%= review.rating.to_i %> stars
          </div>
          <% end %>
        </div>
        <hr>
    </div>

    <div class="form-container">
      <div class="form-fields">

      <%= simple_form_for([@yacht, @review], url: yacht_reviews_path(@yacht), remote: true)  do |f|%>
      <%= f.input :content %>
      <%= f.input :rating %>
      <%= f.submit class: 'btn-search'%>
      <% end %>
      </div>
    </div>
  </div>

</div>
<div class="mapWrapper mt-5">
  <div id="map"style="width: 100%; height: 600px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>